const Data=[
  {
    "id": 1,
    "Name": "Peaky Blinders",
    "Platform": "Netflix",
    "Image": "https://iospoilero.wordpress.com/wp-content/uploads/2018/03/81e1ihpphql-_sl1500_.jpg?w=1040",
    "Seasons": 6,
    "Episodes": 36,
    "Duration": 60,
    "Plot": "Set in 1920s Birmingham, it follows the Shelby family and their rise in the criminal underworld.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 2,
    "Name": "Vikings",
    "Platform": "Netflix / Prime Video",
    "Image": "https://m.media-amazon.com/images/M/MV5BOTFmZmExYTEtYmE0Mi00MzRmLWE4ZDYtOThiNzNlOTIyODljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "Seasons": 6,
    "Episodes": 89,
    "Duration": 44,
    "Plot": "Chronicles the legendary Ragnar Lothbrok and his descendants in Viking conquests and expansions.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 3,
    "Name": "Ozark",
    "Platform": "Netflix",
    "Image": "https://images.justwatch.com/poster/10929406/s718/ozark.jpg",
    "Seasons": 4,
    "Episodes": 44,
    "Duration": 60,
    "Plot": "A financial advisor drags his family into a dangerous money-laundering scheme for a drug cartel.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 4,
    "Name": "Ragnarok",
    "Platform": "Netflix",
    "Image": "https://m.media-amazon.com/images/M/MV5BYzhlZTU4MTgtMTViNS00OWJhLTg2N2QtYmVhZmNhZjJmOTkxXkEyXkFqcGc@._V1_.jpg",
    "Seasons": 3,
    "Episodes": 18,
    "Duration": 45,
    "Plot": "In a small Norwegian town, a teenager discovers he is the reincarnation of Thor and must face modern giants.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 5,
    "Name": "Coach Carter",
    "Platform": "Netflix / Disney+",
    "Image": "https://i0.wp.com/thehotjem.com/wp-content/uploads/2025/04/81a69db66ef02db8f44e835d1b8dff3d222740ffbd5a5040644f739fc529b18e.jpg?fit=900%2C1200&ssl=1",
    "Seasons": 1,
    "Episodes": 1,
    "Duration": 136,
    "Plot": "A coach imposes discipline and values on his basketball players in a tough neighborhood, even at the cost of winning.",
    "Current": false,
    "Type": "film",
    "Favorite": false
  },
  {
    "id": 6,
    "Name": "Squid Game",
    "Platform": "Netflix",
    "Image": "https://www.asianfeast.org/wp-content/uploads/2021/10/squid-game.jpeg",
    "Seasons": 3,
    "Episodes": 22,
    "Duration": 60,
    "Plot": "A group of indebted people participate in deadly games to win a huge cash prize.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 7,
    "Name": "The Sandman",
    "Platform": "Netflix",
    "Image": "https://sm.ign.com/ign_it/tv/s/sandman-1/sandman-1_nspx.jpg",
    "Seasons": 2,
    "Episodes": 11,
    "Duration": 55,
    "Plot": "After decades of imprisonment, the Lord of Dreams must regain his powers and restore balance between realms.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 8,
    "Name": "You",
    "Platform": "Netflix",
    "Image": "https://m.media-amazon.com/images/I/81Qw5nY7vKL._AC_UF1000,1000_QL80_.jpg",
    "Seasons": 4,
    "Episodes": 40,
    "Duration": 50,
    "Plot": "A manipulative and obsessive man dangerously falls in love with women he encounters, leading to extreme consequences.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 9,
    "Name": "Narcos",
    "Platform": "Netflix",
    "Image": "https://m.media-amazon.com/images/I/91jkF8kLQqL._AC_UF894,1000_QL80_.jpg",
    "Seasons": 3,
    "Episodes": 30,
    "Duration": 50,
    "Plot": "Based on real events, it tells the rise and fall of famous drug lords, including Pablo Escobar.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 10,
    "Name": "The Big Short",
    "Platform": "Netflix",
    "Image": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p12157971_p_v13_al.jpg",
    "Seasons": 1,
    "Episodes": 1,
    "Duration": 130,
    "Plot": "A group of investors discovers the subprime mortgage crisis and bets against the American financial system.",
    "Current": false,
    "Type": "film",
    "Favorite": false
  },
  {
    "id": 11,
    "Name": "Rush",
    "Platform": "Netflix / Prime Video",
    "Image": "https://pad.mymovies.it/filmclub/2011/06/203/locandina.jpg",
    "Seasons": 1,
    "Episodes": 1,
    "Duration": 123,
    "Plot": "The rivalry between Formula 1 drivers Niki Lauda and James Hunt reaches epic levels in the 1970s.",
    "Current": false,
    "Type": "film",
    "Favorite": false
  },
  {
    "id": 12,
    "Name": "The Boys",
    "Platform": "Prime Video",
    "Image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8nTHbkR8hRo2JHZ7L1lXa5VWCatbPHWeY8A&s",
    "Seasons": 4,
    "Episodes": 32,
    "Duration": 60,
    "Plot": "In a world where superheroes abuse their power, a group of vigilantes tries to stop them with brutal methods.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 13,
    "Name": "The Queen's Gambit",
    "Platform": "Netflix",
    "Image": "https://upload.wikimedia.org/wikipedia/en/1/12/The_Queen%27s_Gambit_%28miniseries%29.png",
    "Seasons": 1,
    "Episodes": 7,
    "Duration": 60,
    "Plot": "A young orphan discovers a remarkable talent for chess while battling addiction and personal pressures.",
    "Current": false,
    "Type": "series",
    "Favorite": true
  },
  {
    "id": 14,
    "Name": "Breaking Bad",
    "Platform": "Netflix",
    "Image": "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "Seasons": 5,
    "Episodes": 62,
    "Duration": 47,
    "Plot": "A chemistry teacher becomes a meth producer to secure his family's financial future.",
    "Current": false,
    "Type": "series",
    "Favorite": true
  },
  {
    "id": 15,
    "Name": "Better Call Saul",
    "Platform": "Netflix",
    "Image": "https://m.media-amazon.com/images/I/81gwy45Dx7L._AC_UF894,1000_QL80_.jpg",
    "Seasons": 6,
    "Episodes": 63,
    "Duration": 55,
    "Plot": "Prequel to Breaking Bad, follows the transformation of lawyer Jimmy McGill into the cynical Saul Goodman.",
    "Current": false,
    "Type": "series",
    "Favorite": false
  },
  {
    "id": 16,
    "Name": "Django Unchained",
    "Platform": "Netflix / Sky",
    "Image": "https://m.media-amazon.com/images/I/81IVfnsVtIL._AC_UF894,1000_QL80_.jpg",
    "Seasons": 1,
    "Episodes": 1,
    "Duration": 165,
    "Plot": "A former slave seeks revenge against his oppressors in the Wild West.",
    "Current": false,
    "Type": "film",
    "Favorite": true
  },
  {
    "id": 17,
    "Name": "Fight Club",
    "Platform": "Disney+ / Prime Video",
    "Image": "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "Seasons": 1,
    "Episodes": 1,
    "Duration": 139,
    "Plot": "A bored office worker and a soap salesman form a secret club where men release their anger.",
    "Current": false,
    "Type": "film",
    "Favorite": true
  },
  {
    "id": 18,
    "Name": "The Irishman",
    "Platform": "Netflix",
    "Image": "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/The_Irishman_poster.jpg/250px-The_Irishman_poster.jpg",
    "Seasons": 1,
    "Episodes": 1,
    "Duration": 209,
    "Plot": "A mafia hitman recounts his life and involvement in the disappearance of union leader Jimmy Hoffa.",
    "Current": false,
    "Type": "film",
    "Favorite": true
  },
 {'id': 19,
    'Name': 'Game of Thrones',
    'Platform': 'HBO / Now / Sky',
    'Image': 'https://m.media-amazon.com/images/M/MV5BMTNhMDJmNmYtNDQ5OS00ODdlLWE0ZDAtZTgyYTIwNDY3OTU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    'Seasons': 8,
    'Episodes': 73,
    'Duration': 60, // average minutes per episode
    'Plot': 'Various noble houses fight for the Iron Throne while an ancient threat rises in the North, capable of destroying the world.',
    'Current': false,
    'Type': 'series',
    'Favorite': true
  },
  {
    'id': 20,
    'Name': 'Barry Seal - American Made',
    'Platform': 'Prime Video / Netflix / Apple TV',
    'Image': 'https://pad.mymovies.it/filmclub/2016/10/074/locandina.jpg',
    'Seasons': 1,
    'Episodes': 1,
    'Duration': 115, // minutes
    'Plot': 'The true story of Barry Seal, a U.S. pilot who became a CIA operative and drug smuggler for South American cartels in the 1980s.',
    'Current': false,
    'Type': 'film',
    'Favorite': false
  },
  {
  "id": 21,
  "Name": "Tulsa King",
  "Platform": "Paramount+",
  "Image": "https://m.media-amazon.com/images/I/81x5n3zT82L.jpg",
  "Seasons": 1,
  "Episodes": 9,
  "Duration": 40,
  "Plot": "After 25 years in prison, a New York mafia capo is sent to Tulsa, Oklahoma, to establish a new criminal empire.",
  "Current": true,
  "Type": "series",
  "Favorite": false
},
{
  "id": 22,
  "Name": "Nightcrawler",
  "Platform": "Prime Video",
  "Image": "https://m.media-amazon.com/images/I/916TmQhLhXL._AC_UF894,1000_QL80_.jpg",
  "Seasons": 1,
  "Episodes": 1,
  "Duration": 117,
  "Plot": "A driven young man stumbles into the world of Los Angeles crime journalism and blurs the line between observer and participant to become the star of his own story.",
  "Current": false,
  "Type": "film",
  "Favorite": false
},
{
  "id": 23,
  "Name": "Reacher",
  "Platform": "Prime Video",
  "Image": "https://m.media-amazon.com/images/I/61-kMCKFTGL._AC_UF894,1000_QL80_.jpg",
  "Seasons": 3,
  "Episodes": 24,
  "Duration": 49,
  "Plot": "Ex‑military policeman Jack Reacher travels across America, unknown to the authorities, fighting corruption and injustice wherever he finds it.",
  "Current": false,
  "Type": "series",
  "Favorite": false
},
{
  "id": 24,
  "Name": "Nobody",
  "Platform": "Prime Video",
  "Image": "https://mr.comingsoon.it/imgdb/locandine/big/59484.jpg",
  "Seasons": 1,
  "Episodes": 1,
  "Duration": 92,
  "Plot": "An overlooked dad and husband, mistaken for a nobody, finds himself in a violent conflict after a home invasion exposes dark secrets he's spent years trying to keep hidden.",
  "Current": false,
  "Type": "film",
  "Favorite": false
},
{
  "id": 25,
  "Name": "El Camino: A Breaking Bad Movie",
  "Platform": "Netflix",
  "Image": "https://m.media-amazon.com/images/M/MV5BYTYxMjI2YzUtODQ5Mi00M2JmLTlmNzItOTlkM2MyM2ExM2RlXkEyXkFqcGc@._V1_.jpg",
  "Seasons": 1,
  "Episodes": 1,
  "Duration": 122,
  "Plot": "In the aftermath of his dramatic escape from captivity, Jesse Pinkman must confront his past in order to forge some kind of future. " ,
  "Current": false,
  "Type": "film",
  "Favorite": false
},
{
  "id": 26,
  "Name": "All Quiet on the Western Front",
  "Platform": "Netflix",
  "Image": "https://pad.mymovies.it/filmclub/2022/09/024/locandina.jpg",
  "Seasons": 1,
  "Episodes": 1,
  "Duration": 148,
  "Plot": "A young German soldier's eagerness to serve his country quickly fades when he witnesses the horrors of combat on the Western Front during World War I.",
  "Current": false,
  "Type": "film",
  "Favorite": false
},
{
  "id": 27,
  "Name": "The Last Kingdom",
  "Platform": "Netflix",
  "Image": "https://m.media-amazon.com/images/M/MV5BMjE1MzYzNjk3OF5BMl5BanBnXkFtZTgwMzk0MzYwNzE@._V1_.jpg",
  "Seasons": 5,
  "Episodes": 46,
  "Duration": 57,
  "Plot": "A Saxon‑born warrior raised by Vikings must choose where his loyalty lies as Alfred the Great defends his kingdom from Norse invaders.",
  "Current": false,
  "Type": "series",
  "Favorite": false
},
{
  "id": 28,
  "Name": "Vikings: Valhalla",
  "Platform": "Netflix",
  "Image": "https://m.media-amazon.com/images/M/MV5BYWFjYmMxMjMtMGE2ZC00YWZhLTgzNDYtYTA3ODA2MDg2NTA4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "Seasons": 3,
  "Episodes": 24,
  "Duration": 50,
  "Plot": "A century after the era of Ragnar, legendary Viking warriors — Leif Eriksson, Freydís Eiríksdóttir and Harald Hardrada — rise to forge their own destiny and confront a changing Europe and the end of the Viking age.",
  "Current": false,
  "Type": "series",
  "Favorite": false
}

]

export default Data